### ISSUE TITLE
Feature Request: Mapping Function Prefix

### ISSUE THREAD

**Issue by jbritain** [camplowell/block_wrangler#1]
When the mapping glsl file is generated, it contains a load of functions with names directly equivalent to the names given. This means that if I have a mapping for 'water', I get a function `water`. If I already have a function called `water`, this is a conflict, so I need to rename one of them. What I propose is an optional and customisable prefix, such that 'water' could be generated as `ipbr_is_water`, for example, with the prefix being `ipbr_is_`.

**Comment by camplowell** [comment]
Thanks for the feedback! I'll put something to that end in the next revision.

I'm thinking of going even a little more general, and letting you pass in a lambda. That would allow you to use whatever naming conventions you want, whether it's `is_flag`, `Flag`, etc.

**Comment by camplowell** [comment]
Fixed as of the release of alpha v0.0.4!
